# ------------------------------
# Operating System @ NTHU CS
# ------------------------------
project:
  type: website          # switched from "book"
  output-dir: _site
  resources:
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"
    - "*.txt*"

filters:
  - jiumi
  - color

website:
  title: "Operating System (2025 Fall)"
  back-to-top-navigation: true
  favicon: "images/orange.png"
  site-url: ""            # add when you deploy

  sidebar:
    collapse-level: 1
    style: "docked"
    search: true
    contents:
      - text: "OS 2025 Fall"
        href: index.qmd
      - section: "Worksheet 2"
        href: weeks/w2.qmd
        contents:
          - handouts/env_setup.qmd
      - section: "Worksheet 3"
        href: weeks/w3.qmd
        contents:
          - handouts/unix.qmd
          - labs/mini-cloud.qmd
          - labs/process-creation.qmd
      - section: "Worksheet 4"
        href: weeks/w4.qmd
        contents:
          - handouts/privilege.qmd
          - labs/path-traversal.qmd
          - labs/process-address-space.qmd
          - labs/linking.qmd
      - section: "Worksheet 5"
        href: weeks/w5.qmd
        contents:
          - labs/pipe-passwords.qmd
          - labs/pipe-dup.qmd
          - labs/fifo.qmd
      - section: "Worksheet 6"
        href: weeks/w6.qmd
        contents:
          - handouts/scheduler.qmd
          - labs/process-state.qmd
          - labs/pipe-pingpong.qmd
      - section: "Worksheet 8"
        href: weeks/w8.qmd
        contents:
          - handouts/buffercache.qmd
          - labs/cat.qmd
      - section: "Worksheet 9"
        href: weeks/w9.qmd
        contents:
          - labs/xv6-intro.qmd
          - labs/xv6-gdb.qmd
          - labs/xv6-syscall.qmd
      - section: "Worksheet 10"
        href: weeks/w10.qmd
        contents:
          - handouts/vm-page-size.qmd
      - section: "Worksheet 11"
        href: weeks/w11.qmd
        contents:
          - labs/xv6-forkbomb.qmd
          - labs/xv6-gdb.qmd
          - labs/xv6-development-env.qmd

  navbar:
    pinned: true
    left:
      - text: Home
        file: index.qmd

      - text: Handouts
        menu:
          - text: "Environment Setup"
            file: handouts/env_setup.qmd
          - text: "Unix"
            file: handouts/unix.qmd
          - text: "Privilege"
            file: handouts/privilege.qmd
          - text: "Scheduler"
            file: handouts/scheduler.qmd
          - text: "Buffer Cache"
            file: handouts/buffercache.qmd
          - text: "Virtual Memory: Page Size"
            file: handouts/vm-page-size.qmd

      - text: Labs
        menu:
          - text: "Mini Cloud"
            file: labs/mini-cloud.qmd
          - text: "Linking"
            file: labs/linking.qmd
          - text: "Process Creation"
            file: labs/process-creation.qmd
          - text: "Process State"
            file: labs/process-state.qmd
          - text: "Process Address Space"
            file: labs/process-address-space.qmd
          - "---"
          - text: "Path Traversal"
            file: labs/path-traversal.qmd
          - text: "Pipe Passwords"
            file: labs/pipe-passwords.qmd
          - text: "Pipe and dup()"
            file: labs/pipe-dup.qmd
          - text: "Pipe Ping-Pong"
            file: labs/pipe-pingpong.qmd
          - text: "FIFO (named pipe)"
            file: labs/fifo.qmd
          - "---"
          - text: "Cat"
            file: labs/cat.qmd
          - "---"
          - text: "xv6 System Call Tracing"
            file: labs/xv6-syscall.qmd

      - text: Admin
        menu:
          - text: Policies
            file: admin/policies.qmd
          - text: Exploratory Projects
            file: admin/explore.qmd
          - text: SD1↓ (燒蛋一下)
            file: admin/waitbutwhy.qmd

    right:
      # - icon: github
      #   href: https://github.com/AtlasOfLivingAustralia/cleaning_data
      - icon: globe
        href: https://elearn.nthu.edu.tw/course/view.php?id=38873


  # --- PAGE FOOTER ---
  page-footer:
    border: true
    left: |
      <img id="footer-cat-left" src="/images/cat-left.png" alt="Cat Left">
    center: |
      <span id="footer-center">Made with ❤️ by Tony, (CC BY 4.0) <br/><span style='font-size: 8px'>Cat source: Freepik and ChatGPT</span></span>
    right: |
      <img id="footer-cat-right" src="/images/cat-right.png" alt="Cat Right">

      

# NTHU CS <a href="https://dcs.site.nthu.edu.tw/">
#   <img src="/images/nthucs-v2.png" style="height:30px;padding:0 10px 5px 10px;">
# </a>
format:
  html:
    mainfont: Montserrat
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#fdf1e5"
    link-external-icon: true
    link-external-newwindow: true
    theme:
      - cat.scss
      - footer-cat.scss
      # - theme.css
      # - theme.scss
      # - minty

execute:
  code-annotations: hover
  number-depth: 3

bibliography:
  - references.bib
  - os.bib
